services:
  jupyter-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    image: beardw/wine-classification:25a308e
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G  
    platform: linux/amd64
