<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prabuddha Tamhane, Harrison Li, Shihan Xu, Wesley Beard">

<title>Wine Classification</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="wine_classifier_files/libs/clipboard/clipboard.min.js"></script>
<script src="wine_classifier_files/libs/quarto-html/quarto.js"></script>
<script src="wine_classifier_files/libs/quarto-html/popper.min.js"></script>
<script src="wine_classifier_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="wine_classifier_files/libs/quarto-html/anchor.min.js"></script>
<link href="wine_classifier_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="wine_classifier_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="wine_classifier_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="wine_classifier_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="wine_classifier_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary"><span class="header-section-number">1</span> Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">3</span> Data</a>
  <ul class="collapse">
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><span class="header-section-number">3.1</span> Data Wrangling</a></li>
  <li><a href="#data-validation" id="toc-data-validation" class="nav-link" data-scroll-target="#data-validation"><span class="header-section-number">3.2</span> Data Validation</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">4</span> Methods</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">5</span> Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#data-structure" id="toc-data-structure" class="nav-link" data-scroll-target="#data-structure"><span class="header-section-number">5.1</span> Data Structure</a></li>
  <li><a href="#overall-univariate-distributions" id="toc-overall-univariate-distributions" class="nav-link" data-scroll-target="#overall-univariate-distributions"><span class="header-section-number">5.2</span> Overall Univariate Distributions</a></li>
  <li><a href="#distributions-of-features-by-wine-type" id="toc-distributions-of-features-by-wine-type" class="nav-link" data-scroll-target="#distributions-of-features-by-wine-type"><span class="header-section-number">5.3</span> Distributions of Features by Wine Type</a></li>
  <li><a href="#pairwise-correlations" id="toc-pairwise-correlations" class="nav-link" data-scroll-target="#pairwise-correlations"><span class="header-section-number">5.4</span> Pairwise Correlations</a></li>
  </ul></li>
  <li><a href="#modeling" id="toc-modeling" class="nav-link" data-scroll-target="#modeling"><span class="header-section-number">6</span> Modeling</a>
  <ul class="collapse">
  <li><a href="#data-splitting" id="toc-data-splitting" class="nav-link" data-scroll-target="#data-splitting"><span class="header-section-number">6.1</span> Data Splitting</a></li>
  <li><a href="#pipeline" id="toc-pipeline" class="nav-link" data-scroll-target="#pipeline"><span class="header-section-number">6.2</span> Pipeline</a></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison"><span class="header-section-number">6.3</span> Model Comparison</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">7</span> Results</a>
  <ul class="collapse">
  <li><a href="#confusion-matrix" id="toc-confusion-matrix" class="nav-link" data-scroll-target="#confusion-matrix"><span class="header-section-number">7.1</span> Confusion Matrix</a></li>
  <li><a href="#test-scoring" id="toc-test-scoring" class="nav-link" data-scroll-target="#test-scoring"><span class="header-section-number">7.2</span> Test Scoring</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">8</span> Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">9</span> References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Wine Classification</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prabuddha Tamhane, Harrison Li, Shihan Xu, Wesley Beard </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="summary" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Summary</h1>
<p>This project illustrates how our team endeavoured to build a classification model to predict whether a wine was red or white based on a set of wine quality features (ex. pH, residual sugars, etc.). Four models were investigated with the best one being RBF SVM, and it performed extremely well on our test data. While there were still false positives and false negatives, indicated by the scores being less than one, this is not of great concern to us. Since we are not dealing with life-threatening or possible adverse outcomes, should a prediction be incorrect, the high level of precision in our model has given us confidence to use it in production.</p>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<p>Red or white? This is a question that countless dinner guests are asked every evening. Some know exactly what they like and others are more open to exploring something new and exciting. And just like the consumer, wine producers have a vested interest in this question. However, they aren’t looking at the wine through a glass, but at the very chemistry that makes up each and every nuanced flavour. They are asking: What does the chemistry say this wine is? Our goal in this analysis is to see if we can develop a machine learning model to predict whether a wine will be classified as either white or red, based on a sample of wine chemical characteristics. This would allow the industry to be able to confirm their wines not only on a visual aspect but on a chemical level as well.</p>
<p>There may be a time that industry producers, small and large-alike, want to dive into how their wines measure up when compared to others. This could be confirming what is already known or helping to make that key distinction when a winemaker creates a blend of white and red and would like to know how best to market their product.</p>
<p>For example, it may be the case that a wine visually looks like a red, but that may not mean it chemically acts like one. Our model will be able to make that distinction and report back what the chemistry says.</p>
<p>Of course, there may be classifications that don’t align with what the wine is visually or the goal of the winemaker. In these cases, it may be due to variation in the model and the prediction probability not being reasonably high for either a red or white. While this may be seen as a disadvantage, it could also provide additional insights regarding the chemical quality of the wine in question. (I.e. It could be produced as a white wine, but with some underlying qualities of red wine.)</p>
<p>With a proper understanding of our model, the input data, and final prediction, we hope that it will provide the wine industry with another way of viewing and marketing their product to the next couple dining out.</p>
</section>
<section id="data" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data</h1>
<p>We are using a dataset of wine quality for wines from the northern region of Portugal (<span class="citation" data-cites="wine_data">C. Cortez Paulo and Reis (<a href="#ref-wine_data" role="doc-biblioref">2009</a>)</span>, originally described in <span class="citation" data-cites="wine_paper">P. Cortez et al. (<a href="#ref-wine_paper" role="doc-biblioref">2009</a>)</span>) that consists of several chemical features: fixed acidity, pH, citric acid, sulphates, residual sugar and several others.</p>
<section id="data-wrangling" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data-wrangling"><span class="header-section-number">3.1</span> Data Wrangling</h2>
<p>To prepare for data analysis, we:</p>
<ul>
<li>combined the red and white wine datasets into a single dataframe,</li>
<li>remove the <em>quality</em> variable to avoid data leakage,</li>
<li>standardized column names,</li>
<li>created a categorical <code>wine_type</code> variable (red vs.&nbsp;white),</li>
<li>created a binary <code>target</code> variable (0 = red, 1 = white).</li>
</ul>
<p>We confirmed that the dataset contains no missing values and falls within the expected measurement ranges described in <span class="citation" data-cites="wine_paper">P. Cortez et al. (<a href="#ref-wine_paper" role="doc-biblioref">2009</a>)</span>. Finally, the data were randomly split into training and test sets.</p>
</section>
<section id="data-validation" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="data-validation"><span class="header-section-number">3.2</span> Data Validation</h2>
<p>Before conducting analysis, we performed a series of validation checks to ensure data quality:</p>
<ul>
<li>verified the presence of all expected variables,</li>
<li>confirmed the absence of missing values,</li>
<li>checked for duplicate rows and removed them when present,</li>
<li>validated numerical ranges using domain knowledge from <span class="citation" data-cites="wine_paper">P. Cortez et al. (<a href="#ref-wine_paper" role="doc-biblioref">2009</a>)</span>,</li>
<li>ensured that the <code>wine_type</code> and <code>target</code> variables contained only valid categories,</li>
<li>ensured that no feature-feature anomalous correlation and target-feature anomalous correlation exists.</li>
</ul>
<p>These checks ensured the dataset was clean, consistent, and suitable for modelling.</p>
</section>
</section>
<section id="methods" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Methods</h1>
<p>All models were implemented using the scikit-learn library (<span class="citation" data-cites="scikit-learn">Pedregosa et al. (<a href="#ref-scikit-learn" role="doc-biblioref">2011</a>)</span>), and Altair (<span class="citation" data-cites="altair">VanderPlas (<a href="#ref-altair" role="doc-biblioref">2018</a>)</span>) was used for visualizations. The analysis makes use of NumPy (<span class="citation" data-cites="numpy">Harris et al. (<a href="#ref-numpy" role="doc-biblioref">2020</a>)</span>) for numerical computations.</p>
</section>
<section id="exploratory-data-analysis" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Exploratory Data Analysis</h1>
<p>This section summarizes the data structure and important statistical properties that are related to the features of this wine classification project.</p>
<section id="data-structure" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="data-structure"><span class="header-section-number">5.1</span> Data Structure</h2>
<p>From <a href="#tbl-data-summary" class="quarto-xref">Table&nbsp;1</a>, there are some key observations:</p>
<ul>
<li><strong>Residual sugar</strong>, <strong>free sulfur dioxide</strong>, and <strong>total sulfur dioxide</strong> have wide ranges and right-skewed distributions with extreme outliers.</li>
<li><strong>pH</strong>, <strong>alcohol</strong>, <strong>density</strong>, <strong>chlorides</strong> and <strong>critic acid</strong> have small standard deviations, showing relatively tight distributions.</li>
</ul>
<p>These statistics provide insight into which variables may separate wine types well. From <a href="#tbl-data-structure" class="quarto-xref">Table&nbsp;2</a>, 11 numerical features with no missing values, which confirms that the dataset is clean and ready for analysis.</p>
<div class="cell" data-execution_count="2">
<div id="tbl-data-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-data-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary statistics for all numerical features in the wine dataset.
</figcaption>
<div aria-describedby="tbl-data-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="28">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Unnamed: 0</th>
<th style="text-align: right;">fixed_acidity</th>
<th style="text-align: right;">volatile_acidity</th>
<th style="text-align: right;">citric_acid</th>
<th style="text-align: right;">residual_sugar</th>
<th style="text-align: right;">chlorides</th>
<th style="text-align: right;">free_sulfur_dioxide</th>
<th style="text-align: right;">total_sulfur_dioxide</th>
<th style="text-align: right;">density</th>
<th style="text-align: right;">pH</th>
<th style="text-align: right;">sulphates</th>
<th style="text-align: right;">alcohol</th>
<th style="text-align: right;">target</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">count</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">4256</td>
</tr>
<tr class="even">
<td style="text-align: left;">mean</td>
<td style="text-align: right;">7.19754</td>
<td style="text-align: right;">0.345301</td>
<td style="text-align: right;">0.314866</td>
<td style="text-align: right;">5.06326</td>
<td style="text-align: right;">0.0567735</td>
<td style="text-align: right;">29.9641</td>
<td style="text-align: right;">113.751</td>
<td style="text-align: right;">0.994537</td>
<td style="text-align: right;">3.22858</td>
<td style="text-align: right;">0.533609</td>
<td style="text-align: right;">10.5558</td>
<td style="text-align: right;">0.742716</td>
</tr>
<tr class="odd">
<td style="text-align: left;">std</td>
<td style="text-align: right;">1.30927</td>
<td style="text-align: right;">0.168979</td>
<td style="text-align: right;">0.146301</td>
<td style="text-align: right;">4.5334</td>
<td style="text-align: right;">0.0364303</td>
<td style="text-align: right;">17.7682</td>
<td style="text-align: right;">56.7417</td>
<td style="text-align: right;">0.00296598</td>
<td style="text-align: right;">0.161483</td>
<td style="text-align: right;">0.148742</td>
<td style="text-align: right;">1.18807</td>
<td style="text-align: right;">0.437188</td>
</tr>
<tr class="even">
<td style="text-align: left;">min</td>
<td style="text-align: right;">3.8</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.98711</td>
<td style="text-align: right;">2.72</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">25%</td>
<td style="text-align: right;">6.4</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right;">0.038</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">0.99226</td>
<td style="text-align: right;">3.12</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">50%</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">0.994685</td>
<td style="text-align: right;">3.22</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">10.4</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">75%</td>
<td style="text-align: right;">7.7</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">7.5</td>
<td style="text-align: right;">0.066</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">154</td>
<td style="text-align: right;">0.99675</td>
<td style="text-align: right;">3.33</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">11.4</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">max</td>
<td style="text-align: right;">15.9</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: right;">1.66</td>
<td style="text-align: right;">65.8</td>
<td style="text-align: right;">0.611</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">440</td>
<td style="text-align: right;">1.03898</td>
<td style="text-align: right;">4.01</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">14.9</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="3">
<div id="tbl-data-structure" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-data-structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Summary of dataset structure, including feature names, entries, null values, and data types.
</figcaption>
<div aria-describedby="tbl-data-structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="29">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Features</th>
<th style="text-align: right;">Total Entries</th>
<th style="text-align: right;">Null Values</th>
<th style="text-align: left;">Data Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">target</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">int64</td>
</tr>
<tr class="even">
<td style="text-align: left;">alcohol</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">chlorides</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
<tr class="even">
<td style="text-align: left;">citric_acid</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">density</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
<tr class="even">
<td style="text-align: left;">fixed_acidity</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">free_sulfur_dioxide</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
<tr class="even">
<td style="text-align: left;">pH</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">residual_sugar</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
<tr class="even">
<td style="text-align: left;">sulphates</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total_sulfur_dioxide</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
<tr class="even">
<td style="text-align: left;">volatile_acidity</td>
<td style="text-align: right;">4256</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">float64</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="overall-univariate-distributions" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="overall-univariate-distributions"><span class="header-section-number">5.2</span> Overall Univariate Distributions</h2>
<div id="fig-univariate-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-univariate-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/hist_univariate_distributions.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-univariate-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Histograms showing the univariate distributions of all numeric chemical features in the wine dataset. Each subplot illustrates the overall shape, skewness, and spread of a single variable.
</figcaption>
</figure>
</div>
<p>We can see from <a href="#fig-univariate-dist" class="quarto-xref">Figure&nbsp;1</a>, many features (e.g.&nbsp;<strong>residual sugar</strong>, <strong>chlorides</strong>, <strong>sulphates</strong>) show right-skewness, which means most wines fall in lower ranges with a few extreme values, whereas <strong>alchohol</strong> is slightly right-skewed, the distribution of <strong>density</strong> and <strong>pH</strong> are similar to Normal distribution.</p>
</section>
<section id="distributions-of-features-by-wine-type" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="distributions-of-features-by-wine-type"><span class="header-section-number">5.3</span> Distributions of Features by Wine Type</h2>
<div id="fig-kde-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kde-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/distributions_of_features.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kde-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Kernel density estimates of each numerical feature, comparing distributions of red (0) and white (1) wines.
</figcaption>
</figure>
</div>
<p>From <a href="#fig-kde-dist" class="quarto-xref">Figure&nbsp;2</a>, we can see differences between red (0) and white (1) wine:</p>
<ul>
<li>Overall, most features for both wine types show <strong>strongly right-skewed distributions</strong>. The distribution of <strong>pH</strong> looks close to bell-shaped. For pH, the <strong>red wines have higher pH than white wines</strong>, so the whites are more acidic.</li>
<li>For <strong>fixed_acidity</strong>, <strong>volatile_acidity</strong>, <strong>citric_acid</strong>, <strong>chlorides</strong>, and <strong>sulphates</strong>, the <strong>white wines have higher density at the lower end of the scale</strong>, so whites here look “lighter” and cleaner on these chemistry dimensions.</li>
<li><strong>Alcohol</strong> levels tend to be higher in <strong>red wines</strong>, while white wines peak at slightly lower alcohol values. Combined with their higher pH, this suggests that whites are lighter but sweeter and more acidic.</li>
</ul>
</section>
<section id="pairwise-correlations" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="pairwise-correlations"><span class="header-section-number">5.4</span> Pairwise Correlations</h2>
<div id="fig-correlation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/pairwise_correlations.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Correlation heatmap showing pairwise relationships among the wine chemical features.
</figcaption>
</figure>
</div>
<p>From <a href="#fig-correlation" class="quarto-xref">Figure&nbsp;3</a>, we can observe some overall correlation patterns:</p>
<ul>
<li><strong>Density</strong> is strongly positively correlated with <strong>residual sugar</strong>, and <strong>free sulfur dioxide</strong> is strongly correlated with <strong>total sulfur dioxide</strong>.</li>
<li><strong>Alcohol</strong> is negatively correlated with <strong>density</strong>, consistent with wine chemistry.</li>
<li><strong>pH</strong> is negatively correlated with <strong>fixed acidity</strong>, showing the expected inverse relationship.</li>
</ul>
</section>
</section>
<section id="modeling" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Modeling</h1>
<section id="data-splitting" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="data-splitting"><span class="header-section-number">6.1</span> Data Splitting</h2>
<p>First, we splited the data into training and testing sets. Meanwhile, the <code>wine_type</code> column has been encoded into the binary <code>target</code> variable and was therefore removed. Then, the resulting dataset was separated into feature dataframe and the target vector for use in modeling the steps.</p>
</section>
<section id="pipeline" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="pipeline"><span class="header-section-number">6.2</span> Pipeline</h2>
<p>Since all predictors are numerical and models such as KNN and SVMs are distance-based, <code>StandardScaler</code> from sklearn was applied to all those features so as to ensure all features have equal weights in the model.</p>
</section>
<section id="model-comparison" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="model-comparison"><span class="header-section-number">6.3</span> Model Comparison</h2>
<p>Overall, from <a href="#tbl-cv-df" class="quarto-xref">Table&nbsp;3</a>, most classifiers achieved strong predictive performance, except for the <code>DummyClassifier</code>, which is expected, since it is a baseline that does not use feature information.</p>
<div class="cell" data-execution_count="4">
<div id="tbl-cv-df" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cv-df-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Cross-validated performance metrics for all evaluated classification models, including mean fit time, score time, training accuracy, and test accuracy with standard deviations across folds.
</figcaption>
<div aria-describedby="tbl-cv-df-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="30">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: left;">fit_time</th>
<th style="text-align: left;">score_time</th>
<th style="text-align: left;">test_score</th>
<th style="text-align: left;">train_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">dummy</td>
<td style="text-align: left;">0.0006 (+/- 0.0006)</td>
<td style="text-align: left;">0.0005 (+/- 0.0001)</td>
<td style="text-align: left;">0.7427 (+/- 0.0001)</td>
<td style="text-align: left;">0.7427 (+/- 0.0000)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Decision Tree</td>
<td style="text-align: left;">0.0127 (+/- 0.0004)</td>
<td style="text-align: left;">0.0007 (+/- 0.0000)</td>
<td style="text-align: left;">0.9810 (+/- 0.0061)</td>
<td style="text-align: left;">0.9998 (+/- 0.0002)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">KNN</td>
<td style="text-align: left;">0.0024 (+/- 0.0001)</td>
<td style="text-align: left;">0.0110 (+/- 0.0003)</td>
<td style="text-align: left;">0.9930 (+/- 0.0037)</td>
<td style="text-align: left;">0.9947 (+/- 0.0009)</td>
</tr>
<tr class="even">
<td style="text-align: left;">RBF SVM</td>
<td style="text-align: left;">0.0183 (+/- 0.0018)</td>
<td style="text-align: left;">0.0061 (+/- 0.0002)</td>
<td style="text-align: left;">0.9958 (+/- 0.0032)</td>
<td style="text-align: left;">0.9969 (+/- 0.0008)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Logistic Regression</td>
<td style="text-align: left;">0.0037 (+/- 0.0018)</td>
<td style="text-align: left;">0.0007 (+/- 0.0001)</td>
<td style="text-align: left;">0.9925 (+/- 0.0034)</td>
<td style="text-align: left;">0.9937 (+/- 0.0006)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Among all those evaluated models, the <strong>RBF-SVM</strong> achieved the highest validation performance and showed the smallest variability across folds, with mean CV train score of 0.9969, and test score of 0.9958, indicating a strong balance between accuracy and stability. This suggests that <strong>non-linear decision boundaries</strong> may better capture the structure of the one classification compared to linear methods.</p>
</section>
</section>
<section id="results" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Results</h1>
<section id="confusion-matrix" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="confusion-matrix"><span class="header-section-number">7.1</span> Confusion Matrix</h2>
<p>To further evaluate model behavior, we examined the confusion matrices for each classifier. The matrix provided a detailed view of how well each model distinguishes between red wine (label = 0) and white wine (label = 1). Overall, we especially focus on the confusion matrix for RBF SVM model, and all models—except the DummyClassifier—achieve very strong separation between the two classes:</p>
<ul>
<li><strong>Decision Tree, KNN, RBF SVM, and Logistic Regression</strong> all show very low wrong counts for both classes.</li>
<li><strong>RBF SVM</strong> performs especially well, from <a href="#fig-matrix" class="quarto-xref">Figure&nbsp;4</a> we can see that it produced near-perfect predictions with only a small number of false positives and false negatives.</li>
</ul>
<div id="fig-matrix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/confusion_matrix.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Confusion matrix for the RBF SVM model.
</figcaption>
</figure>
</div>
<p>These results show that those models are highly capable of distinguishing between wine types, with <strong>RBF SVM providing the most consistent and accurate classification</strong>.</p>
</section>
<section id="test-scoring" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="test-scoring"><span class="header-section-number">7.2</span> Test Scoring</h2>
<p>We next evaluated each model on the test set using <strong>accuracy, recall, precision, and F1 score</strong>. These metrics allow us to assess the generalization performance of each classifier beyond the training data and the result is shown in <a href="#tbl-test-metrics" class="quarto-xref">Table&nbsp;4</a> below.</p>
<div class="cell" data-execution_count="5">
<div id="tbl-test-metrics" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-test-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Performance metrics (Accuracy, Recall, Precision, F1) for the best performing model (RBF SVM) on the test set.
</figcaption>
<div aria-describedby="tbl-test-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="31">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">accuracy</th>
<th style="text-align: right;">recall</th>
<th style="text-align: right;">precision</th>
<th style="text-align: right;">f1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">dummy</td>
<td style="text-align: right;">0.75188</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.75188</td>
<td style="text-align: right;">0.858369</td>
</tr>
<tr class="even">
<td style="text-align: left;">Decision Tree</td>
<td style="text-align: right;">0.976504</td>
<td style="text-align: right;">0.9875</td>
<td style="text-align: right;">0.981366</td>
<td style="text-align: right;">0.984424</td>
</tr>
<tr class="odd">
<td style="text-align: left;">KNN</td>
<td style="text-align: right;">0.986842</td>
<td style="text-align: right;">0.99125</td>
<td style="text-align: right;">0.99125</td>
<td style="text-align: right;">0.99125</td>
</tr>
<tr class="even">
<td style="text-align: left;">RBF SVM</td>
<td style="text-align: right;">0.993421</td>
<td style="text-align: right;">0.99625</td>
<td style="text-align: right;">0.995006</td>
<td style="text-align: right;">0.995628</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Logistic Regression</td>
<td style="text-align: right;">0.989662</td>
<td style="text-align: right;">0.9925</td>
<td style="text-align: right;">0.993742</td>
<td style="text-align: right;">0.993121</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The results show a clear trend:</p>
<ul>
<li>The <strong>DummyClassifier</strong> performs the worst, with accuracy around 0.7519 and substantially lower precision and F1.</li>
<li><strong>Decision Tree, KNN, and Logistic Regression</strong> all perform well, achieving accuracy scores above 0.9765 and balanced precision/recall values.</li>
<li><strong>RBF SVM</strong> outperforms all other models, achieving the highest scores in accuracy, recall, precision, and F1—demonstrating excellent predictive capability and strong generalization.</li>
</ul>
</section>
</section>
<section id="discussion" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Discussion</h1>
<p>We found that all of the models that we tested preformed much better than our Dummy Classifier. Subsequently, comparing our models individually, each one performed well. However, the model that had the highest cross-validation score was RBF SVM at 0.9958. Since all models scored high (&gt;0.99), we included them in calculating accuracy, recall, precision and f1 on our test data. Here again, we see RBF SVM performing the best with the highest scores in each one of these metrics (0.9934, 0.9962, 0.995, and 0.9956 respectively).</p>
<p>The metric of focus for our analysis was accuracy. Our primary aim was to ensure that we were correctly predicting whether or not a wine was red or white. Although we were looking towards accuracy, we can also see from our confusion matrices that the test recall and precision scores were high resulting in the lowest false positives and false negatives. While our model was not being explicitly optimized regarding precision and recall, having these relatively small incorrect predictions from our training data and higher test scores adds to the robustness and our confidence of the model.</p>
<p>All four of our potential models exceeded our expectations. We expected them to do well, however, were pleased with the final results and scoring. There were some key features that led us to expect at least one well performing model. These were highlighted during our Exploratory Data Analysis and can be seen in our Distributions of Different Features by Wine Type and Pairwise Correlations visualizations. By analyzing the various density plots, we were able to see that there were several noticeable differences between red and white wines for several different features. There appeared to be several distributions with varying levels of overlap that increased our confidence that any potential model would be able to correctly predict red or white with a reasonable level of accuracy. For example, we saw different distributions for the volatile acidity and pH features. Our pairwise correlations showed a varying level of correlations among all the different features. This was an interesting part of the analysis as highly correlated free sulfur dioxide and sulfates made sense, while the negatively correlated alcohol and density got us to think deeper into the chemical nature of the wine.</p>
<p>These findings allow us to present a model that we can offer to winemakers and industry stakeholders to use in their business needs. Without having to spend the resources and time to create new wine products, a business can focus on the important features and from there decide on what wine to produce. For example, if a business was interested in making and marketing a wine that was low sugar and low in acidity (along with the other features), our model would help determine the type that should be produced. This is in addition to using the model to predict what type of wine an already produced wine is.</p>
<p>Our current analysis was only for the classification between two different types of wine: red and white. It would be interesting to see if we could expand this to include additional types of wine. We could look at including quality data for rose and sparkling wines. Additionally, if this new model worked well, it would be interesting to see if we could further generalize and make an all-purpose model that could be used to predict different types of alcohols based solely on chemical quality composition. This could possibly be useful, not only in the liquor industry, but in tangential industries that rely on models to predict unknown substances from a sample. (For example, forensics comes to mind.)</p>
</section>
<section id="references" class="level1 unnumbered" data-number="9">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">9 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-wine_data" class="csl-entry" role="listitem">
Cortez, Cerdeira, Paulo, and J. Reis. 2009. <span>“<span>Wine Quality</span>.”</span> UCI Machine Learning Repository.
</div>
<div id="ref-wine_paper" class="csl-entry" role="listitem">
Cortez, Paulo, António Cerdeira, Fernando Almeida, Telmo Matos, and José Reis. 2009. <span>“Modeling Wine Preferences by Data Mining from Physicochemical Properties.”</span> <em>Decision Support Systems</em> 47 (4): 547–53. https://doi.org/<a href="https://doi.org/10.1016/j.dss.2009.05.016">https://doi.org/10.1016/j.dss.2009.05.016</a>.
</div>
<div id="ref-numpy" class="csl-entry" role="listitem">
Harris, Charles R, K Jarrod Millman, Stéfan J van der Walt, Ralf Gommers, Pauli Virtanen, David Cournapeau, Eric Wieser, et al. 2020. <span>“<span class="nocase">Array programming with NumPy</span>.”</span> <em>Nature</em> 585 (7825): 357–62. <a href="https://doi.org/10.1038/s41586-020-2649-2">https://doi.org/10.1038/s41586-020-2649-2</a>.
</div>
<div id="ref-scikit-learn" class="csl-entry" role="listitem">
Pedregosa, F., G. Varoquaux, A. Gramfort, V. Michel, B. Thirion, O. Grisel, M. Blondel, et al. 2011. <span>“<span class="nocase">Scikit-learn: Machine Learning in Python</span>.”</span> <em>Journal of Machine Learning Research</em> 12: 2825–30.
</div>
<div id="ref-altair" class="csl-entry" role="listitem">
VanderPlas, Jake. 2018. <span>“Altair: Interactive Statistical Visualizations for Python.”</span> <em>Journal of Open Source Software</em> 3 (7825, 32): 1057. <a href="https://doi.org/10.21105/joss.01057">https://doi.org/10.21105/joss.01057</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>