---
title: Wine Classification
jupyter: python3
---



## Summary
This project illustrates how our team endeavoured to build a classification model to predict whether a wine was red or white based on a set of wine quality features (ex. pH, residual sugars, etc.).  Four models were investigated with the best one being RBF SVM. It performed extremely well on our test data, with an accuracy of 0.9969 and f1 score of 0.9979. While there were still false positives and false negatives, indicated by the scores being less than one, this is not of great concern to us. Since we are not dealing with life-threatening or possible adverse outcomes, should a prediction be incorrect, the high level of precision in our model has given us confidence to use it in production.

# Introduction
Red or white? This is a question that countless dinner guests are asked every evening. Some know exactly what they like and others are more open to exploring something new and exciting. And just like the consumer, wine producers have a vested interest in this question. However, they aren’t looking at the wine through a glass, but at the very chemistry that makes up each and every nuanced flavour. They are asking: What does the chemistry say this wine is?

Our goal in this analysis is to see if we can develop a machine learning model to predict whether a wine will be classified as either white or red, based on a sample of wine chemical characteristics. This would allow the industry to be able to confirm their wines not only on a visual aspect but on a chemical level as well. We are using a dataset of wine quality for wines from the northern region of Portugal that consists of several chemical features: fixed acidity, pH, citric acid, sulphates, residual sugar and several others.

There may be a time that industry producers, small and large-alike, want to dive into how their wines measure up when compared to others. This could be confirming what is already known or helping to make that key distinction when a winemaker creates a blend of white and red and would like to know how best to market their product.

For example, it may be the case that a wine visually looks like a red, but that may not mean it chemically acts like one. Our model will be able to make that distinction and report back what the chemistry says.

Of course, there may be classifications that don’t align with what the wine is visually or the goal of the winemaker. In these cases, it may be due to variation in the model and the prediction probability not being reasonably high for either a red or white. While this may be seen as a disadvantage, it could also provide additional insights regarding the chemical quality of the wine in question. (I.e. It could be produced as a white wine, but with some underlying qualities of red wine.) 

With a proper understanding of our model, the input data, and final prediction, we hope that it will provide the wine industry with another way of viewing and marketing their product to the next couple dining out.

# Imports

```{python}
import numpy as np
if not hasattr(np, "Inf"):
    np.Inf = np.inf
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.dummy import DummyClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.tree import DecisionTreeClassifier


from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.compose import make_column_transformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import (
    cross_validate,
    train_test_split,
    cross_val_predict
)
import os
import pandera.pandas as pa
os.environ["DISABLE_PANDERA_IMPORT_WARNING"] = "True"
from pandera.errors import SchemaErrors
```

# Exploratory Data Analysis

## Part 1: Data Ingestion & Data Wrangling  
First, we download the raw red and white wine datasets programmatically into `data/raw/` to ensure reproducibility.

Since the raw data has no NA values, this section begins with loading the red wine and white wine datasets from `data/raw/` directory separately, adding labels indicating the wine type, and combining them into a single unified dataset for further analysis.  

add run in README.md
```bash
python scripts/download_data.py
```

```{python}
path = "../data/raw/wine-raw.csv"
df = pd.read_csv(path)
```

Below adding two new columns:  
 - `wine_type`: `red` for red wine, `white` for white wine. This column is used only for EDA and will not be included as a feature for classification.
 - `target`: `0` for red wine, `1` for white wine, which is the variable to be predicted.

```{python}
# drop quality if it exists
# the continuous target quality is not within our scope of interest in the classification model
if 'quality' in df.columns:
    df = df.drop(columns=['quality'])

# rename color to wine_type
df = df.rename(columns={"color":"wine_type"})
df["target"] = df["wine_type"].replace({
    "red": 0, 
    "white": 1
})
```

Then merging the datasets and removing `quality` column:
 - two datasets are concatenated row-wise into one dataframe called `df_merge`
 - `quality` score is highly informative and could lead to data leakage if used as a feature when predicting wine type, therefore, we drop it from `df_merge`.

```{python}
# df_merge = pd.concat([df_red, df_white], axis=0).reset_index(drop=True)
if 'quality' in df.columns:
    df = df.drop(columns=["quality"])
df.columns = df.columns.str.replace(" ", "_")
df = df.rename(columns={"color":"wine_type"})
df
```

```{python}
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(df, test_size=0.2, random_state=123)
```

## Part 1.2 Data Validation 
This section performs the validation checks to ensure the data entered into the pipeline is standardized and validated to ensure smooth functioning of the analysis performed in the next sections.

```{python}
train_df["wine_type"].value_counts()
```

#### 1.2.1 Check for empty Dataframe:

```{python}
if len(df) == 0:
    raise ValueError("The merged dataset is empty.")
```

#### 1.2.2 Check for expected columns

```{python}
# Note: 'quality' was dropped, so we check for the remaining ones
expected_columns = {
    "fixed_acidity", "volatile_acidity", "citric_acid", "residual_sugar",
    "chlorides", "free_sulfur_dioxide", "total_sulfur_dioxide", "density",
    "pH", "sulphates", "alcohol", "wine_type", "target"
}

if not expected_columns.issubset(df.columns):
    missing = expected_columns - set(df.columns)
    raise ValueError(f"Missing columns: {missing}")
```

#### 1.2.3 Check for missing values

```{python}
#The notebook mentions raw data has no NAs, but good to verify
if df.isnull().any().any():
    raise ValueError("Unexpected missing values found in the dataset.")
```

#### 1.2.4 Check for correct data types in each column
- Ensure every column contains the correct data type
#### 1.2.5 Duplicate Observation Check
- Seems like there's duplicate observations for some reason
- dropped duplicated rows and re-validated the data
#### 1.2.6 Check for outlier or anonymous values
The range of outlier is determined by the paper of the dataset: 
[https://repositorium.uminho.pt/server/api/core/bitstreams/f3dd2aa2-9eda-4eba-b50e-6306a0bd0c66/content](https://repositorium.uminho.pt/server/api/core/bitstreams/f3dd2aa2-9eda-4eba-b50e-6306a0bd0c66/content) 

[Cortez et al., 2009]

```{python}
#| error: true
# the range of checks is determined by referring to the paper related to the dataset

schema = pa.DataFrameSchema(
    {   
        # data type check
        "fixed_acidity": pa.Column(float, pa.Check.between(0, 20), nullable=True), 
        "volatile_acidity": pa.Column(float, pa.Check.between(0, 2), nullable=True), 
        "citric_acid": pa.Column(float, pa.Check.between(0, 2), nullable=True), 
        "residual_sugar": pa.Column(float, pa.Check.between(0, 100), nullable=True),
        "chlorides": pa.Column(float, pa.Check.between(0, 1), nullable=True), 
        "free_sulfur_dioxide": pa.Column(float, pa.Check.between(0, 500), nullable=True), 
        "total_sulfur_dioxide": pa.Column(float, pa.Check.between(0, 600), nullable=True), 
        "density": pa.Column(float, pa.Check.between(0.8, 1.2), nullable=True),
        "pH": pa.Column(float, pa.Check.between(0, 6), nullable=True), 
        "sulphates": pa.Column(float, pa.Check.between(0, 3), nullable=True), 
        "alcohol": pa.Column(float, pa.Check.between(5, 20), nullable=True), 
        
        # targets should not be nullable
        "wine_type": pa.Column(str, pa.Check.isin(['white', 'red']), nullable=False), 
        "target": pa.Column(int, pa.Check.isin([0, 1]), nullable=False)
    },
    checks=[
        # duplicate observation check
        pa.Check(lambda df: ~df.duplicated().any(), error="Duplicate rows found."),
        pa.Check(lambda df: ~(df.isna().all(axis=1)).any(), error="Empty rows found.")
    ]
)

try:
    schema.validate(df, lazy=True)
except SchemaErrors as se:
    if "Duplicate rows found." in str(se):
        print("Duplicate rows detected — drop duplicates and re-validate.")
        df = df.drop_duplicates()
        schema.validate(df, lazy=True)  # re-validate after dropping duplicates
    else:
        # raise SchemaErrors if it is other issue
        raise se
```

#### 1.2.7 Check for correct category levels 

```{python}
wine_schema = pa.DataFrameSchema(
    {
        "wine_type": pa.Column(
            str,
            pa.Check.isin(["red", "white"]),
            nullable=False
        )
    }
)

validated_df = wine_schema.validate(df, lazy=True)
print("wine_type category level validation passed!")
```

#### 1.2.8 Check for expected distribution for target variable

Since we have already counted samples in each category of the target variable at the beginning of **[Part 1.2: Data Validation](#Part-1.2-Data-Validation)**, and in **[Part 2: Exploratory Data Analysis - 2: Overall Univariate Distributions](2.-Overall-Univariate-Distributions)**, we also visualized the distribution of the target variable using histograms.  
Based on these results, the minority class accounts for **1267 / (3930 + 1267) ≈ 24.4%** of the data, which is well above 0.1.   
Therefore, the distribution of the target variable is not imbalanced, and no single class dominates the dataset, which confirms that the target variable follows the expected distribution and passes this check.  

#### 1.2.8 Correlation check between explanatory and response variables.

see the check result below in: [Part 2: Exploratory Data Analysis - 5. Target - Feature anomalous correlation check](5.-Target---Feature-anomalous-correlation-check)

#### 1.2.9 Correlation check just between feature(explanatory) variables

see the check result below in: [Part 2: Exploratory Data Analysis - 6. Feature - Feature anomalous correlation check](6.-Feature---Feature-anomalous-correlation-check)

The final combined dataset contains:
 - all numeric chemical features
 - `wine_type` (categorical, only for EDA visualization), with 4,898 white wine samples and 1599 red wine samples.
 - `target` (binary variable for classification)  
  
Now this dataframe is not imbalanced and clean, it is ready for EDA and modeling.

## Part 2: Exploratory Data Analysis  
This section summarizes the data structure and important statistical properties that are related to the features of this wine classification project.
### 1. Data Structure

```{python}
df_info = pd.DataFrame({
    "Features": train_df.columns,
    "Total Entries": train_df.count(),
    "Null Values": train_df.isnull().sum(),
    "Data Type": train_df.dtypes
}).sort_values(by=["Data Type", "Features"])
df_info
```

The `.info()` output shows:  
 - No missing values
 - 11 numerical features

Confirms that the dataset is clean and ready for analysis.

```{python}
df_summary = train_df.describe()
df_summary
```

Using `.describe()` to check summary statistics for all numerical variables.  
Key observations:
 - **Residual sugar**, **free sulfur dioxide**, and **total sulfur dioxide** have wide ranges and right-skewed distributions with extreme outliers.
 - **pH**, **alcohol**, **density**, **chlorides** and **critic acid** have small standard deviations, showing relatively tight distributions.

These statistics provide insight into which variables may separate wine types well.

### 2. Overall Univariate Distributions
Overall histogram patterns:
 - Many features (e.g. **residual sugar**, **chlorides**, **sulphates**) show right-skewness, which means most wines fall in lower ranges with a few extreme values, whereas **alchohol** is slightly right-skewed.
 - The distribution of **dnesity** and **pH** are similar to Normal distribution.

```{python}
import altair as alt
alt.data_transformers.enable("vegafusion")

numeric_cols = train_df.select_dtypes('number').columns.tolist()

plots = []
for col in numeric_cols:
    plot = alt.Chart(train_df).mark_bar().encode(
        alt.X(
            col, type="quantitative",
            bin=alt.Bin(maxbins=40),
            title=f"{col} (binned)"
        ),
        alt.Y("count()",title="Count").stack(False),
    ).properties(
        width=140,
        height=110
    )
    plots.append(plot)

hist_plot = alt.concat(*plots, columns=3).properties(
    title="Univariate Distributions of Numeric Features"
).configure_title(fontSize=20)
hist_plot
```

### 3. Distributions of Features by Wine Type
Key distribution differences between red (0) and white (1) wine:
- Overall, most features for both wine types show **strongly right-skewed distributions**. The distribution of **pH** looks close to bell-shaped. For pH, the **red wines have higher pH than white wines**, so the whites are more acidic.
- For **fixed_acidity**, **volatile_acidity**, **citric_acid**, **chlorides**, and **sulphates**, the **white wines have higher density at the lower end of the scale**, so whites here look "lighter" and cleaner on these chemistry dimensions.
- **Alcohol** levels tend to be higher in **red wines**, while white wines peak at slightly lower alcohol values. Combined with their higher pH, this suggests that whites are lighter but sweeter and more acidic.

```{python}
plot_2 = []
numeric_cols_2 = numeric_cols.copy()
numeric_cols_2.remove("target")
target_col = "target"

for col2 in numeric_cols_2:
    kde_plot = alt.Chart(train_df).transform_density(
        density=col2,
        groupby=[target_col],
        as_=[f"{col2}", "kde_density"],
        steps=200
    ).mark_line().encode(
        alt.X(f"{col2}:Q", title=col2),
        alt.Y("kde_density:Q", title="KDE Density").stack(False),
        alt.Color(f"{target_col}:N", title="Wine Type")
    ).properties(
        width=130,
        height=100
    )
    plot_2.append(kde_plot)

kde_final = alt.concat(*plot_2, columns=3).resolve_scale(
    x="independent",
    y="independent"
).properties(
    title="Distributions of Different Features by Wine Type"
).configure_title(fontSize=20)
kde_final
```

### 4. Pairwise Correlations
Overall correlation patterns:
 - **Density** is strongly positively correlated with **residual sugar**, and **free sulfur dioxide** is strongly correlated with **total sulfur dioxide**.
 - **Alcohol** is negatively correlated with **density**, consistent with wine chemistry.
 - **pH** is negatively correlated with **fixed acidity**, showing the expected inverse relationship.

```{python}
corr = train_df[numeric_cols].corr().reset_index().melt("index")
corr.columns = ["feature_x", "feature_y", "correlation"]

heatmap = (
    alt.Chart(corr)
    .mark_rect()
    .encode(
        alt.X("feature_x:N", title="Feature X"),
        alt.Y("feature_y:N", title="Feature Y"),
        color=alt.Color(
            "correlation:Q", scale=alt.Scale(domain=(-1, 1),scheme="purpleorange"),
            title="Correlation"
        ),
        tooltip=["feature_x", "feature_y", "correlation"]
    )
    .properties(width=300, height=300, title="Correlation Heatmap")
)

heatmap = heatmap.properties(
    title="Correlation Heatmap of Wine Chemical Features"
).configure_title(fontSize=15)
heatmap
```

### 5. Target - Feature anomalous correlation check

```{python}
import deepchecks
from deepchecks.tabular import Dataset
from deepchecks.tabular.checks import FeatureLabelCorrelation, FeatureFeatureCorrelation
```

```{python}
train_ck = train_df.drop(columns=["wine_type"])
wine_train_ds = Dataset(
    train_ck,
    label="target",        
    cat_features=[]         
)

# Check anomalous correlation between features and the target
check_feat_lab_corr = FeatureLabelCorrelation().add_condition_feature_pps_less_than(0.9)
check_feat_lab_corr_result = check_feat_lab_corr.run(dataset=wine_train_ds)

# Raise error if any condition fails
if not check_feat_lab_corr_result.passed_conditions():
    raise ValueError("Feature–label correlation exceeds the acceptable threshold (< 0.9).")

print("Feature–label correlation validation passed!")
```

### 6. Feature - Feature anomalous correlation check

```{python}
check_feat_feat_corr = (
    FeatureFeatureCorrelation()
    .add_condition_max_number_of_pairs_above_threshold(
        threshold=0.92,   # correlation over 0.92 is considered problematic
        n_pairs=0         # allow 0 problematic pairs
    )
)

check_feat_feat_corr_result = check_feat_feat_corr.run(dataset=wine_train_ds)

# Raise error if condition fails
if not check_feat_feat_corr_result.passed_conditions():
    raise ValueError("Feature–feature correlation exceeds acceptable limits (>0.92).")

print("Feature–feature correlation validation passed!")
```

# Classification Model

- Split data into train and test set
- Drop `wine_type` since it is converted into target as binary column
- seperate data set into features and target

```{python}
train_df, test_df = train_test_split(df.drop(columns=["wine_type"]), test_size=0.2, random_state=123)

X_train, y_train = train_df.drop(columns=["target"]), train_df["target"]
X_test, y_test = test_df.drop(columns=["target"]), test_df["target"]
```

### Pipeline
- Since all features are numerical, `StandardScaler` from sklearn is applied to all features to ensure all features have equal weights in the classifier model.
- iterate through each model to find the optimal classifier model

```{python}
preprocessor = StandardScaler()

models = {
    "dummy": DummyClassifier(random_state = 123),
    "Decision Tree": DecisionTreeClassifier(random_state = 123),
    "KNN": KNeighborsClassifier(),
    "RBF SVM": SVC(random_state = 123),
    "Logistic Regression": LogisticRegression(max_iter = 2000, random_state = 123),
}
```

The following code for `mean_std_cross_val_scores` is adapted from DSCI 571 lab 2

```{python}
def mean_std_cross_val_scores(model, X_train, y_train, **kwargs):
    """
    Returns mean and std of cross validation

    Parameters
    ----------
    model :
        scikit-learn model
    X_train : numpy array or pandas DataFrame
        X in the training data
    y_train :
        y in the training data

    Returns
    ----------
        pandas Series with mean scores from cross_validation
    """

    scores = cross_validate(model, X_train, y_train, **kwargs)

    mean_scores = pd.DataFrame(scores).mean()
    std_scores = pd.DataFrame(scores).std()
    out_col = []

    for i in range(len(mean_scores)):
        out_col.append((f"%0.4f (+/- %0.4f)" % (mean_scores.iloc[i], std_scores.iloc[i])))

    return pd.Series(data=out_col, index=mean_scores.index)
```

### Iterate through each model

```{python}
results_dict = {}

for model_name, model in models.items():
    pipe = make_pipeline(preprocessor, model)
    results_dict[model_name] = mean_std_cross_val_scores(
        pipe, X_train, y_train, cv = 5, return_train_score = True
    )

results_df = pd.DataFrame(results_dict).T
results_df
```

The performance of all models are pretty similar for all models except for the Dummy classifier.
While RBF SVM performs the best with minimum standard deviation in validation score.

# Results

### Confusion Matrix for each model

```{python}
for model_name, model in models.items():
    pipe = make_pipeline(preprocessor, model)
    ConfusionMatrixDisplay(confusion_matrix(y_train, cross_val_predict(pipe, X_train, y_train))).plot(cmap='Blues')
    plt.title("Model: {}\nLabels: 0 = red, 1 = white ".format(model_name))
    
```

### Scoring on test data
- other scoring metrics are calculated on the test data since the accuracy is pretty similar for all models

```{python}
from sklearn.metrics import recall_score, precision_score, accuracy_score
from collections import defaultdict
score_dict = defaultdict(dict)

def calculate_f1(precision, recall):
    """F1 = 2 * precision * recall / (precision + recall)"""
    return 2 * precision * recall / (precision + recall)

for model_name, model in models.items():
    pipe = make_pipeline(preprocessor, model)
    pipe.fit(X_train, y_train)
    prediction = pipe.predict(X_test)

    accuracy = accuracy_score(y_test, prediction)
    recall = recall_score(y_test, prediction)
    precision = precision_score(y_test, prediction)
    
    score_dict[model_name]["accuracy"] = accuracy
    score_dict[model_name]["recall"] = recall
    score_dict[model_name]["precision"] = precision
    score_dict[model_name]["f1"] = calculate_f1(precision, recall)

pd.DataFrame(score_dict).T
```

The RBF SVM model performs the best on the test data as expected

# Discussion
We found that all of the models that we tested preformed much better than our Dummy Classifier. Subsequently, comparing our models individually, each one performed well. However, the model that had the highest cross-validation score was RBF SVM at 0.9952. Since all models scored high (>0.99), we included them in calculating accuracy, recall, precision and f1 on our test data. Here again, we see RBF SVM performing the best with the highest scores in each one of these metrics (0.9969, 0.9989, 0.9969, and 0.9979 respectively).

The metric of focus for our analysis was accuracy. Our primary aim was to ensure that we were correctly predicting whether or not a wine was red or white. Although we were looking towards accuracy, we can also see from our confusion matrices that the test recall and precision scores were high resulting in the lowest false positives and false negatives (20 and 5, during training). While our model was not being explicitly optimized regarding precision and recall, having these relatively small incorrect predictions from our training data and higher test scores adds to the robustness and our confidence of the model.

All four of our potential models exceeded our expectations. We expected them to do well, however, were pleased with the final results and scoring. There were some key features that led us to expect at least one well performing model. These were highlighted during our Exploratory Data Analysis and can be seen in our Distributions of Different Features by Wine Type and Pairwise Correlations visualizations. By analyzing the various density plots, we were able to see that there were several noticeable differences between red and white wines for several different features. There appeared to be several distributions with varying levels of overlap that increased our confidence that any potential model would be able to correctly predict red or white with a reasonable level of accuracy. For example, we saw different distributions for the volatile acidity and pH features. Our pairwise correlations showed a varying level of correlations among all the different features. This was an interesting part of the analysis as highly correlated free sulfur dioxide and sulfates made sense, while the negatively correlated alcohol and density got us to think deeper into the chemical nature of the wine.

These findings allow us to present a model that we can offer to winemakers and industry stakeholders to use in their business needs. Without having to spend the resources and time to create new wine products, a business can focus on the important features and from there decide on what wine to produce. For example, if a business was interested in making and marketing a wine that was low sugar and low in acidity (along with the other features), our model would help determine the type that should be produced. This is in addition to using the model to predict what type of wine an already produced wine is.

Our current analysis was only for the classification between two different types of wine: red and white. It would be interesting to see if we could expand this to include additional types of wine. We could look at including quality data for rose and sparkling wines. Additionally, if this new model worked well, it would be interesting to see if we could further generalize and make an all-purpose model that could be used to predict different types of alcohols based solely on chemical quality composition. This could possibly be useful, not only in the liquor industry, but in tangential industries that rely on models to predict unknown substances from a sample. (For example, forensics comes to mind.)

# References
Cortez, P., Cerdeira, A.L., Almeida, F., Matos, T., & Reis, J. (2009). Modeling wine preferences by data mining from physicochemical properties. Decis. Support Syst., 47, 547-553.

Cortez, P., Cerdeira, A., Almeida, F., Matos, T., & Reis, J. (2009). Wine Quality [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C56S3T.

Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V., Vanderplas, J., Passos, A., Cournapeau, D., Brucher, M., Perrot, M., & Duchesnay, E. (2011). Scikit-learn: Machine Learning in Python. *Journal of Machine Learning Research*, *12*, 2825–2830.

VanderPlas et al., (2018). Altair: Interactive Statistical Visualizations for Python. Journal of Open Source Software, 3(32), 1057, https://doi.org/10.21105/joss.01057


